### ISSUE TITLE
search function ignores the "enable searching for locations" setting

### ISSUE THREAD

**Issue by gpgmailencrypt** [nextcloud/integration_openstreetmap#1]
when I disable the above setting, searching in nextcloud will still lead to a search result. This still happens after logout/login

**Comment by julien-nc** [comment]
Thanks for the bug report. This was a stupid mistake. But when fixing it, I realized we have another problem.

The smart picker actually uses the OSM unified search provider. So if it's disabled, it does not work anymore in the picker as well.

Luckily in the search provider context, we can determine if the search was triggered from the picker or from the unified search menu. So now, if searching in OSM is disabled, it still works in the picker.

This will be included in the next release which is coming soon.

Feel free to reopen if needed.

**Comment by Luticus** [comment]
One other thing that would be great is if the search enabled thing was disabled by default or if there was an admin way to completely disable it server wide.

**Comment by julien-nc** [comment]
There is now an admin setting to globally disable the unified search provider. If disabled, a warning is shown in the user settings and the checkbox is disabled.
If enabled by the admin, the user-specific value is used.

This search provider toggle is now disabled by default for admins and users.
I kind of agree this unified search provider is useless except when it's used in the smart picker.
Thanks for the suggestions.

**Comment by julien-nc** [comment]
v1.0.4 is out

**Comment by Luticus** [comment]
You are awesome! Very much appreciate the response and the changes! Thanks!
