### ISSUE TITLE
What does "OsmAnd" means?

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/integration_openstreetmap#5]
https://github.com/nextcloud/integration_openstreetmap/blob/9fc8d7a5c86f81ced5e3b78c4bd4e0e17e9a81c6/src/views/PointCustomPickerElement.vue#L79

Need context for translators.

Please add comment to source or improve string.

**Comment by daffydock** [comment]
OsmAnd  is an acronym. 
Open Street Maps Automated Navigation Directions

REF:
https://osmand.net/
https://github.com/osmandapp/OsmAnd

Guess someone can do a PR for it.
